// Applies migrations generated by `npm run db:generate` to DATABASE_URL.
// Usage: npm run db:migrate — and, on every deploy, as the first half of
// `vercel-build` (PLAN.md §1.14).
//
// Same driver rule as src/db/index.ts (§1.13): Neon over HTTP in production,
// node-postgres against a local or CI server. Both migrators read the same
// ./drizzle folder and the same __drizzle_migrations bookkeeping table, so a
// database migrated by one is migrated as far as the other is concerned.
import "dotenv/config";
import { drizzle as drizzleNeon } from "drizzle-orm/neon-http";
import { migrate as migrateNeon } from "drizzle-orm/neon-http/migrator";
import { drizzle as drizzlePg } from "drizzle-orm/node-postgres";
import { migrate as migratePg } from "drizzle-orm/node-postgres/migrator";
import { neon } from "@neondatabase/serverless";
import { Pool } from "pg";
import { resolveDriver } from "./driver";

const url = process.env.DATABASE_URL;
const driver = resolveDriver(url);
if (!url) throw new Error("DATABASE_URL is not set — see .env.example.");

const migrationsFolder = "./drizzle";

if (driver === "neon") {
  await migrateNeon(drizzleNeon(neon(url)), { migrationsFolder });
} else {
  const pool = new Pool({ connectionString: url });
  try {
    await migratePg(drizzlePg(pool), { migrationsFolder });
  } finally {
    await pool.end();
  }
}

console.log(`Migrations applied (${driver}).`);
process.exit(0);
